### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by v0369012** [kaist-ina/BWA-MEME#2]
Hello! We faced a **difficulty** when we tried to **install BWA-MEME** on a linux server (bwa-mem2 already installed).

We followed the installation steps and got errors at `make -j32 arch=avx512`.
It showed many warnings and **two errors**.

The **two errors** are 
`src/LearnedIndex_seeding.cpp:468:5: error: ‘__builtin_expect_with_probability’ was not declared in this scope`
`src/LearnedIndex_seeding.cpp:565:5: error: ‘__builtin_expect_with_probability’ was not declared in this scope`

How can we solve the problem? Thank you.

**Comment by quito418** [comment]
Hi,

It seems builtin_* functions are generating errors during compilation.

The functions were used to check if there is any further optimization that can be made (found it does not have impact on performance). 

I just modified the code and committed it in the master branch (removed those __builtin functions).

Can you check if it compiles?

Hope these help!

**Comment by v0369012** [comment]
Thanks for your reply!
I updated your code and ran it again.
I got the different errors:

libbwa.a(LearnedIndex_seeding.o): In function `learned_index_load(char const*, char const*, char const*, double)':
/usr/include/c++/8/bits/fs_path.h:185: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/include/c++/8/bits/fs_path.h:185: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:119: bwa-mem2] Error 1

**Comment by quito418** [comment]
That's interesting,

Can you tell me your OS and g++,  gcc version?

I used gcc version 9.3.0, it seems like it can be a gcc version issue.

**Comment by v0369012** [comment]
OS: CentOS Linux release 8.2.2004 (Core)
g++: 8.3.1
gcc: 8.3.1

Any other requirement ?

**Comment by quito418** [comment]
This may be because gcc < 9 requires a separate library libstdc++fs for std::filesystem. ( https://github.com/CLIUtils/CLI11/issues/445 )

And even if the library is added, it seems it can still have errors according to some stackflow questions.

I think upgrading the **GCC to version 9 is the best solution for now**.

Can you follow the link below to install gcc9 in centos.

### Installing GCC9 - Install gcc9 with dnf 
https://stackoverflow.com/questions/61590926/how-to-install-gcc-g-9-on-centos-8-docker-centoslatest

also, FYI

### When GCC9 is already installed, enable it
https://unix.stackexchange.com/questions/585154/how-to-install-gcc-9-x-on-rhel8

**Comment by v0369012** [comment]
Thanks for your comment!
We install gcc version to 9.3.0 and it works now.

**Comment by quito418** [comment]
Glad to hear that!
