### ISSUE TITLE
SEQ and QUAL are of different length - mode1

### ISSUE THREAD

**Issue by christopher-schroeder** [kaist-ina/BWA-MEME#23]
Hey,

due to lower memory on a different server, I was running bwa-meme (v1.0.6) mode1.
Samtools sort throws

`[E::sam_parse1] SEQ and QUAL are of different length`

I thought this was fixed in 1.0.6 but maybe only for mode3?

Best
Christo

**Comment by quito418** [comment]
Thank you for bringing the error to our attention. 

We did not encounter issues with mode1 in [Issue 21](https://github.com/kaist-ina/BWA-MEME/issues/21), as the error was specifically limited to mode3 at that time. I just checked mode1 and mode3 runs fine with the datasets from previous issue.

I think the current issue is a different error. In order to reproduce the error, could you please provide the bam file and reference genome that you used? (you can use [my cloud](https://o365kaist-my.sharepoint.com/:f:/g/personal/tom418_office_kaist_ac_kr/Eh5Y1BTrOXpJoOawmBnWHiMBRysD1QE_OThNuRuZL293Lw?e=AOHXrz))

Thanks
Youngmok
